#pragma once
#include <stdint.h>
#include "constants.h"

// Simple Font for rendering digits 0-9
const uint8_t font_digits[10][5] = {
    {0x3E, 0x51, 0x49, 0x45, 0x3E}, // 0
    {0x00, 0x42, 0x7F, 0x40, 0x00}, // 1
    {0x42, 0x61, 0x51, 0x49, 0x46}, // 2
    {0x21, 0x41, 0x45, 0x4B, 0x31}, // 3
    {0x18, 0x14, 0x12, 0x7F, 0x10}, // 4
    {0x27, 0x45, 0x45, 0x45, 0x39}, // 5
    {0x3C, 0x4A, 0x49, 0x49, 0x30}, // 6
    {0x01, 0x71, 0x09, 0x05, 0x03}, // 7
    {0x36, 0x49, 0x49, 0x49, 0x36}, // 8
    {0x06, 0x49, 0x49, 0x29, 0x1E}  // 9
};

// 5x5 Block font for uppercase letters A-Z
const uint8_t font_letters[26][5] = {
    {0x7E, 0x11, 0x11, 0x11, 0x7E}, // A
    {0x7F, 0x49, 0x49, 0x49, 0x36}, // B
    {0x3E, 0x41, 0x41, 0x41, 0x22}, // C
    {0x7F, 0x41, 0x41, 0x22, 0x1C}, // D
    {0x7F, 0x49, 0x49, 0x49, 0x41}, // E
    {0x7F, 0x09, 0x09, 0x09, 0x01}, // F
    {0x3E, 0x41, 0x49, 0x49, 0x7A}, // G
    {0x7F, 0x08, 0x08, 0x08, 0x7F}, // H
    {0x00, 0x41, 0x7F, 0x41, 0x00}, // I
    {0x20, 0x40, 0x41, 0x3F, 0x01}, // J
    {0x7F, 0x08, 0x14, 0x22, 0x41}, // K
    {0x7F, 0x40, 0x40, 0x40, 0x40}, // L
    {0x7F, 0x02, 0x0C, 0x02, 0x7F}, // M
    {0x7F, 0x04, 0x08, 0x10, 0x7F}, // N
    {0x3E, 0x41, 0x41, 0x41, 0x3E}, // O
    {0x7F, 0x09, 0x09, 0x09, 0x06}, // P
    {0x3E, 0x41, 0x51, 0x21, 0x5E}, // Q
    {0x7F, 0x09, 0x19, 0x29, 0x46}, // R
    {0x46, 0x49, 0x49, 0x49, 0x31}, // S
    {0x01, 0x01, 0x7F, 0x01, 0x01}, // T
    {0x3F, 0x40, 0x40, 0x40, 0x3F}, // U
    {0x1F, 0x20, 0x40, 0x20, 0x1F}, // V
    {0x7F, 0x20, 0x18, 0x20, 0x7F}, // W
    {0x63, 0x14, 0x08, 0x14, 0x63}, // X
    {0x07, 0x08, 0x70, 0x08, 0x07}, // Y
    {0x61, 0x51, 0x49, 0x45, 0x43}  // Z
};

// Retro Pixel Art Sprites (8x8)
// Each value is an RGB565 color code. 0x0000 (Black) is treated as transparent.

// Player Ship Sprite (R-Type Style)
const uint16_t sprite_player[8][8] = {
    {C_TRANS,  C_TRANS,  C_TRANS,  C_METAL,  C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS},
    {C_TRANS,  C_TRANS,  C_METAL,  C_CYAN,   C_CYAN,   C_TRANS,  C_TRANS,  C_TRANS},
    {C_ORANGE, C_METAL,  C_METAL,  C_METAL,  C_CYAN,   C_CYAN,   C_CYAN,   C_TRANS},
    {C_ORANGE, C_METAL,  C_METAL,  C_METAL,  C_METAL,  C_METAL,  C_CYAN,   COLOR_WHITE},
    {C_ORANGE, C_METAL,  C_METAL,  C_METAL,  C_METAL,  C_METAL,  C_CYAN,   COLOR_WHITE},
    {C_ORANGE, C_METAL,  C_METAL,  C_METAL,  C_CYAN,   C_CYAN,   C_CYAN,   C_TRANS},
    {C_TRANS,  C_TRANS,  C_METAL,  C_CYAN,   C_CYAN,   C_TRANS,  C_TRANS,  C_TRANS},
    {C_TRANS,  C_TRANS,  C_TRANS,  C_METAL,  C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS}
};

// Enemy Alien UFO Sprite (Space Invaders / Galaga Style)
const uint16_t sprite_enemy[8][8] = {
    {C_TRANS,  C_TRANS,  COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS,  C_TRANS},
    {C_TRANS,  COLOR_RED, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_RED, C_TRANS},
    {COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED},
    {C_CYAN,   COLOR_RED, C_CYAN,   COLOR_RED, COLOR_RED, C_CYAN,   COLOR_RED, C_CYAN},
    {C_CYAN,   C_CYAN,   C_CYAN,   C_CYAN,   C_CYAN,   C_CYAN,   C_CYAN,   C_CYAN},
    {C_TRANS,  C_TRANS,  COLOR_RED, C_TRANS,  C_TRANS,  COLOR_RED, C_TRANS,  C_TRANS},
    {C_TRANS,  COLOR_RED, C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  COLOR_RED, C_TRANS},
    {COLOR_RED, C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  COLOR_RED}
};

// Diver Alien UFO Sprite (Magenta/Yellow variant for high visibility)
const uint16_t sprite_enemy_diver[8][8] = {
    {C_TRANS,  C_TRANS,  COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS,  C_TRANS},
    {C_TRANS,  COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, C_TRANS},
    {COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA},
    {COLOR_YELLOW,   COLOR_MAGENTA, COLOR_YELLOW,   COLOR_MAGENTA, COLOR_MAGENTA, COLOR_YELLOW,   COLOR_MAGENTA, COLOR_YELLOW},
    {COLOR_YELLOW,   COLOR_YELLOW,   COLOR_YELLOW,   COLOR_YELLOW,   COLOR_YELLOW,   COLOR_YELLOW,   COLOR_YELLOW,   COLOR_YELLOW},
    {C_TRANS,  C_TRANS,  COLOR_MAGENTA, C_TRANS,  C_TRANS,  COLOR_MAGENTA, C_TRANS,  C_TRANS},
    {C_TRANS,  COLOR_MAGENTA, C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  COLOR_MAGENTA, C_TRANS},
    {COLOR_MAGENTA, C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  COLOR_MAGENTA}
};

// Shooter Alien UFO Sprite (Yellow/Red blaster variant)
const uint16_t sprite_enemy_shooter[8][8] = {
    {C_TRANS,  C_TRANS,  COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, C_TRANS,  C_TRANS},
    {C_TRANS,  COLOR_YELLOW, COLOR_WHITE, COLOR_RED,  COLOR_RED,  COLOR_WHITE, COLOR_YELLOW, C_TRANS},
    {COLOR_YELLOW, COLOR_YELLOW, COLOR_RED,   COLOR_RED,  COLOR_RED,  COLOR_RED,   COLOR_YELLOW, COLOR_YELLOW},
    {COLOR_RED,    COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED},
    {COLOR_RED,    C_TRANS,      COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, C_TRANS,      COLOR_RED},
    {C_TRANS,  C_TRANS,  COLOR_YELLOW, C_TRANS,  C_TRANS,  COLOR_YELLOW, C_TRANS,  C_TRANS},
    {C_TRANS,  COLOR_YELLOW, C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  COLOR_YELLOW, C_TRANS},
    {COLOR_YELLOW, C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  COLOR_YELLOW}
};

// Laser Bullet Sprite
const uint16_t sprite_bullet[4][8] = {
    {C_TRANS,  C_ORANGE, C_ORANGE, C_ORANGE, C_ORANGE, C_ORANGE, C_ORANGE, C_TRANS},
    {C_ORANGE, COLOR_YELLOW, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, C_ORANGE},
    {C_ORANGE, COLOR_YELLOW, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, C_ORANGE},
    {C_TRANS,  C_ORANGE, C_ORANGE, C_ORANGE, C_ORANGE, C_ORANGE, C_ORANGE, C_TRANS}
};

// 16x16 Boss Mothership Sprite (Galaga Style)
const uint16_t sprite_boss[16][16] = {
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_RED, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS},
    {C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS},
    {COLOR_RED, COLOR_RED, C_CYAN, COLOR_RED, C_CYAN, COLOR_RED, COLOR_RED, C_CYAN, C_CYAN, COLOR_RED, COLOR_RED, C_CYAN, COLOR_RED, C_CYAN, COLOR_RED, COLOR_RED},
    {COLOR_RED, COLOR_RED, C_CYAN, COLOR_RED, C_CYAN, COLOR_RED, COLOR_RED, C_CYAN, C_CYAN, COLOR_RED, COLOR_RED, C_CYAN, COLOR_RED, C_CYAN, COLOR_RED, COLOR_RED},
    {COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED},
    {COLOR_RED, C_CYAN, C_CYAN, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_RED, C_CYAN, C_CYAN, COLOR_RED},
    {C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, C_CYAN, C_CYAN, C_CYAN, C_CYAN, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_RED, C_TRANS, C_TRANS, COLOR_RED, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS}
};

// 16x16 Boss Dreadnought Sprite (Purple Carrier)
const uint16_t sprite_boss_dreadnought[16][16] = {
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS},
    {C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS},
    {COLOR_MAGENTA, COLOR_MAGENTA, COLOR_YELLOW, COLOR_MAGENTA, COLOR_YELLOW, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_YELLOW, COLOR_YELLOW, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_YELLOW, COLOR_MAGENTA, COLOR_YELLOW, COLOR_MAGENTA, COLOR_MAGENTA},
    {COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA},
    {COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA},
    {COLOR_MAGENTA, COLOR_YELLOW, COLOR_YELLOW, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_YELLOW, COLOR_YELLOW, COLOR_MAGENTA},
    {C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_MAGENTA, C_TRANS, C_TRANS, COLOR_MAGENTA, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS}
};

// 5x5 Heart Sprite for Lives HUD
const uint16_t sprite_heart[5][5] = {
    {COLOR_RED, COLOR_RED, C_TRANS, COLOR_RED, COLOR_RED},
    {COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED},
    {COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED},
    {C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_RED, C_TRANS, C_TRANS}
};

// 6x6 Shield Power-up Sprite (Blue Sphere Outline)
const uint16_t sprite_powerup_shield[6][6] = {
    {C_TRANS, C_CYAN,  C_CYAN,  C_CYAN,  C_CYAN,  C_TRANS},
    {C_CYAN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_CYAN},
    {C_CYAN,  C_TRANS, COLOR_WHITE, COLOR_WHITE, C_TRANS, C_CYAN},
    {C_CYAN,  C_TRANS, COLOR_WHITE, COLOR_WHITE, C_TRANS, C_CYAN},
    {C_CYAN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_CYAN},
    {C_TRANS, C_CYAN,  C_CYAN,  C_CYAN,  C_CYAN,  C_TRANS}
};

// 6x6 Double Laser Power-up Sprite (Yellow 'P' block)
const uint16_t sprite_powerup_double[6][6] = {
    {COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW},
    {COLOR_YELLOW, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE,  C_TRANS,      COLOR_YELLOW},
    {COLOR_YELLOW, COLOR_WHITE,  C_TRANS,      COLOR_WHITE,  C_TRANS,      COLOR_YELLOW},
    {COLOR_YELLOW, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE,  C_TRANS,      COLOR_YELLOW},
    {COLOR_YELLOW, COLOR_WHITE,  C_TRANS,      C_TRANS,      C_TRANS,      COLOR_YELLOW},
    {COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW}
};

// 6x6 Smart Bomb Power-up Sprite (Purple 'B')
const uint16_t sprite_powerup_bomb[6][6] = {
    {COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA},
    {COLOR_MAGENTA, COLOR_WHITE,   COLOR_WHITE,   C_TRANS,       C_TRANS,       COLOR_MAGENTA},
    {COLOR_MAGENTA, COLOR_WHITE,   COLOR_WHITE,   COLOR_WHITE,   C_TRANS,       COLOR_MAGENTA},
    {COLOR_MAGENTA, COLOR_WHITE,   C_TRANS,       C_TRANS,       COLOR_WHITE,   COLOR_MAGENTA},
    {COLOR_MAGENTA, COLOR_WHITE,   COLOR_WHITE,   COLOR_WHITE,   C_TRANS,       COLOR_MAGENTA},
    {COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA}
};
