#pragma once
#include <stdint.h>
#include "constants.h"

// Simple Font for rendering digits 0-9
const uint8_t font_digits[10][5] = {
    {0x3E, 0x51, 0x49, 0x45, 0x3E}, // 0
    {0x00, 0x42, 0x7F, 0x40, 0x00}, // 1
    {0x42, 0x61, 0x51, 0x49, 0x46}, // 2
    {0x21, 0x41, 0x45, 0x4B, 0x31}, // 3
    {0x18, 0x14, 0x12, 0x7F, 0x10}, // 4
    {0x27, 0x45, 0x45, 0x45, 0x39}, // 5
    {0x3C, 0x4A, 0x49, 0x49, 0x30}, // 6
    {0x01, 0x71, 0x09, 0x05, 0x03}, // 7
    {0x36, 0x49, 0x49, 0x49, 0x36}, // 8
    {0x06, 0x49, 0x49, 0x29, 0x1E}  // 9
};

// 5x5 Block font for uppercase letters A-Z
const uint8_t font_letters[26][5] = {
    {0x7E, 0x11, 0x11, 0x11, 0x7E}, // A
    {0x7F, 0x49, 0x49, 0x49, 0x36}, // B
    {0x3E, 0x41, 0x41, 0x41, 0x22}, // C
    {0x7F, 0x41, 0x41, 0x22, 0x1C}, // D
    {0x7F, 0x49, 0x49, 0x49, 0x41}, // E
    {0x7F, 0x09, 0x09, 0x09, 0x01}, // F
    {0x3E, 0x41, 0x49, 0x49, 0x7A}, // G
    {0x7F, 0x08, 0x08, 0x08, 0x7F}, // H
    {0x00, 0x41, 0x7F, 0x41, 0x00}, // I
    {0x20, 0x40, 0x41, 0x3F, 0x01}, // J
    {0x7F, 0x08, 0x14, 0x22, 0x41}, // K
    {0x7F, 0x40, 0x40, 0x40, 0x40}, // L
    {0x7F, 0x02, 0x0C, 0x02, 0x7F}, // M
    {0x7F, 0x04, 0x08, 0x10, 0x7F}, // N
    {0x3E, 0x41, 0x41, 0x41, 0x3E}, // O
    {0x7F, 0x09, 0x09, 0x09, 0x06}, // P
    {0x3E, 0x41, 0x51, 0x21, 0x5E}, // Q
    {0x7F, 0x09, 0x19, 0x29, 0x46}, // R
    {0x46, 0x49, 0x49, 0x49, 0x31}, // S
    {0x01, 0x01, 0x7F, 0x01, 0x01}, // T
    {0x3F, 0x40, 0x40, 0x40, 0x3F}, // U
    {0x1F, 0x20, 0x40, 0x20, 0x1F}, // V
    {0x7F, 0x20, 0x18, 0x20, 0x7F}, // W
    {0x63, 0x14, 0x08, 0x14, 0x63}, // X
    {0x07, 0x08, 0x70, 0x08, 0x07}, // Y
    {0x61, 0x51, 0x49, 0x45, 0x43}  // Z
};

// Retro Pixel Art Sprites (8x8)
// Each value is an RGB565 color code. 0x0000 (Black) is treated as transparent.

// Player Ship Sprite (R-Type Style)
const uint16_t sprite_player[8][8] = {
    {C_TRANS,  C_TRANS,  C_TRANS,  C_METAL,  C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS},
    {C_TRANS,  C_TRANS,  C_METAL,  C_CYAN,   C_CYAN,   C_TRANS,  C_TRANS,  C_TRANS},
    {C_ORANGE, C_METAL,  C_METAL,  C_METAL,  C_CYAN,   C_CYAN,   C_CYAN,   C_TRANS},
    {C_ORANGE, C_METAL,  C_METAL,  C_METAL,  C_METAL,  C_METAL,  C_CYAN,   COLOR_WHITE},
    {C_ORANGE, C_METAL,  C_METAL,  C_METAL,  C_METAL,  C_METAL,  C_CYAN,   COLOR_WHITE},
    {C_ORANGE, C_METAL,  C_METAL,  C_METAL,  C_CYAN,   C_CYAN,   C_CYAN,   C_TRANS},
    {C_TRANS,  C_TRANS,  C_METAL,  C_CYAN,   C_CYAN,   C_TRANS,  C_TRANS,  C_TRANS},
    {C_TRANS,  C_TRANS,  C_TRANS,  C_METAL,  C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS}
};

// Enemy Alien UFO Sprite (Space Invaders / Galaga Style)
const uint16_t sprite_enemy[8][8] = {
    {C_TRANS,  C_TRANS,  COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS,  C_TRANS},
    {C_TRANS,  COLOR_RED, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_RED, C_TRANS},
    {COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED},
    {C_CYAN,   COLOR_RED, C_CYAN,   COLOR_RED, COLOR_RED, C_CYAN,   COLOR_RED, C_CYAN},
    {C_CYAN,   C_CYAN,   C_CYAN,   C_CYAN,   C_CYAN,   C_CYAN,   C_CYAN,   C_CYAN},
    {C_TRANS,  C_TRANS,  COLOR_RED, C_TRANS,  C_TRANS,  COLOR_RED, C_TRANS,  C_TRANS},
    {C_TRANS,  COLOR_RED, C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  COLOR_RED, C_TRANS},
    {COLOR_RED, C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  COLOR_RED}
};

// Diver Alien UFO Sprite (Magenta/Yellow variant for high visibility)
const uint16_t sprite_enemy_diver[8][8] = {
    {C_TRANS,  C_TRANS,  COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS,  C_TRANS},
    {C_TRANS,  COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, C_TRANS},
    {COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA},
    {COLOR_YELLOW,   COLOR_MAGENTA, COLOR_YELLOW,   COLOR_MAGENTA, COLOR_MAGENTA, COLOR_YELLOW,   COLOR_MAGENTA, COLOR_YELLOW},
    {COLOR_YELLOW,   COLOR_YELLOW,   COLOR_YELLOW,   COLOR_YELLOW,   COLOR_YELLOW,   COLOR_YELLOW,   COLOR_YELLOW,   COLOR_YELLOW},
    {C_TRANS,  C_TRANS,  COLOR_MAGENTA, C_TRANS,  C_TRANS,  COLOR_MAGENTA, C_TRANS,  C_TRANS},
    {C_TRANS,  COLOR_MAGENTA, C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  COLOR_MAGENTA, C_TRANS},
    {COLOR_MAGENTA, C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  COLOR_MAGENTA}
};

// Shooter Alien UFO Sprite (Yellow/Red blaster variant)
const uint16_t sprite_enemy_shooter[8][8] = {
    {C_TRANS,  C_TRANS,  COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, C_TRANS,  C_TRANS},
    {C_TRANS,  COLOR_YELLOW, COLOR_WHITE, COLOR_RED,  COLOR_RED,  COLOR_WHITE, COLOR_YELLOW, C_TRANS},
    {COLOR_YELLOW, COLOR_YELLOW, COLOR_RED,   COLOR_RED,  COLOR_RED,  COLOR_RED,   COLOR_YELLOW, COLOR_YELLOW},
    {COLOR_RED,    COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED},
    {COLOR_RED,    C_TRANS,      COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, C_TRANS,      COLOR_RED},
    {C_TRANS,  C_TRANS,  COLOR_YELLOW, C_TRANS,  C_TRANS,  COLOR_YELLOW, C_TRANS,  C_TRANS},
    {C_TRANS,  COLOR_YELLOW, C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  COLOR_YELLOW, C_TRANS},
    {COLOR_YELLOW, C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  C_TRANS,  COLOR_YELLOW}
};

// Laser Bullet Sprite
const uint16_t sprite_bullet[4][8] = {
    {C_TRANS,  C_ORANGE, C_ORANGE, C_ORANGE, C_ORANGE, C_ORANGE, C_ORANGE, C_TRANS},
    {C_ORANGE, COLOR_YELLOW, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, C_ORANGE},
    {C_ORANGE, COLOR_YELLOW, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, C_ORANGE},
    {C_TRANS,  C_ORANGE, C_ORANGE, C_ORANGE, C_ORANGE, C_ORANGE, C_ORANGE, C_TRANS}
};

// 16x16 Boss Mothership Sprite (Galaga Style)
const uint16_t sprite_boss[16][16] = {
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_RED, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS},
    {C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS},
    {COLOR_RED, COLOR_RED, C_CYAN, COLOR_RED, C_CYAN, COLOR_RED, COLOR_RED, C_CYAN, C_CYAN, COLOR_RED, COLOR_RED, C_CYAN, COLOR_RED, C_CYAN, COLOR_RED, COLOR_RED},
    {COLOR_RED, COLOR_RED, C_CYAN, COLOR_RED, C_CYAN, COLOR_RED, COLOR_RED, C_CYAN, C_CYAN, COLOR_RED, COLOR_RED, C_CYAN, COLOR_RED, C_CYAN, COLOR_RED, COLOR_RED},
    {COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED},
    {COLOR_RED, C_CYAN, C_CYAN, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_RED, C_CYAN, C_CYAN, COLOR_RED},
    {C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, C_CYAN, C_CYAN, C_CYAN, C_CYAN, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_RED, C_TRANS, C_TRANS, COLOR_RED, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS}
};

// 16x16 Boss Dreadnought Sprite (Purple Carrier)
const uint16_t sprite_boss_dreadnought[16][16] = {
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS},
    {C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS},
    {COLOR_MAGENTA, COLOR_MAGENTA, COLOR_YELLOW, COLOR_MAGENTA, COLOR_YELLOW, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_YELLOW, COLOR_YELLOW, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_YELLOW, COLOR_MAGENTA, COLOR_YELLOW, COLOR_MAGENTA, COLOR_MAGENTA},
    {COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA},
    {COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA},
    {COLOR_MAGENTA, COLOR_YELLOW, COLOR_YELLOW, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_YELLOW, COLOR_YELLOW, COLOR_MAGENTA},
    {C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_MAGENTA, C_TRANS, C_TRANS, COLOR_MAGENTA, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS}
};

// 16x16 Boss Phantom Fortress Sprite (Stealth Dark Cyan Fortress with Glowing Core)
const uint16_t sprite_boss_phantom[16][16] = {
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_CYAN, C_CYAN, C_CYAN, C_CYAN, C_CYAN, C_CYAN, C_CYAN, C_CYAN, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, C_CYAN, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, C_CYAN, C_TRANS, C_TRANS},
    {C_TRANS, C_CYAN, C_CYAN, 0x0155, 0x0155, 0x0155, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, 0x0155, 0x0155, 0x0155, C_CYAN, C_CYAN, C_TRANS},
    {C_CYAN, C_CYAN, 0x0155, COLOR_MAGENTA, COLOR_MAGENTA, 0x0155, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, 0x0155, COLOR_MAGENTA, COLOR_MAGENTA, 0x0155, C_CYAN, C_CYAN},
    {C_CYAN, 0x0155, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, 0x0155, C_CYAN, C_CYAN, 0x0155, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, 0x0155, C_CYAN},
    {C_CYAN, 0x0155, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, 0x0155, C_CYAN, C_CYAN, 0x0155, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, 0x0155, C_CYAN},
    {C_CYAN, C_CYAN, 0x0155, COLOR_MAGENTA, COLOR_MAGENTA, 0x0155, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, 0x0155, COLOR_MAGENTA, COLOR_MAGENTA, 0x0155, C_CYAN, C_CYAN},
    {C_TRANS, C_CYAN, C_CYAN, 0x0155, 0x0155, 0x0155, C_CYAN, C_CYAN, C_CYAN, C_CYAN, 0x0155, 0x0155, 0x0155, C_CYAN, C_CYAN, C_TRANS},
    {C_TRANS, C_TRANS, C_CYAN, C_CYAN, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, C_CYAN, C_CYAN, C_CYAN, C_CYAN, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, C_CYAN, C_CYAN, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_CYAN, C_CYAN, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, C_CYAN, C_CYAN, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_CYAN, C_CYAN, COLOR_MAGENTA, COLOR_MAGENTA, C_CYAN, C_CYAN, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_CYAN, C_CYAN, C_CYAN, C_CYAN, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_CYAN, C_CYAN, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS}
};

// 16x16 Boss Mecha Titan Sprite (Armored Gold & Crimson Giant Core)
const uint16_t sprite_boss_titan[16][16] = {
    {C_TRANS, COLOR_YELLOW, COLOR_YELLOW, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS, COLOR_YELLOW, COLOR_YELLOW, C_TRANS},
    {COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW},
    {COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW, COLOR_RED, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_RED, COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW},
    {C_TRANS, COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_YELLOW, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_RED, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_RED, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_RED, COLOR_YELLOW, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_YELLOW, COLOR_RED, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_RED, COLOR_YELLOW, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_YELLOW, COLOR_RED, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_RED, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_RED, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, C_TRANS, C_TRANS},
    {C_TRANS, COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_YELLOW, C_TRANS},
    {COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW},
    {COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS, COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW},
    {C_TRANS, COLOR_YELLOW, COLOR_YELLOW, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_YELLOW, COLOR_YELLOW, C_TRANS}
};

// 16x16 Boss Asteroid Destroyer Sprite (Heavy Rocky Flagship)
const uint16_t sprite_boss_asteroid[16][16] = {
    {C_TRANS, C_TRANS, C_TRANS, C_METAL, C_METAL, C_METAL, C_METAL, C_METAL, C_METAL, C_METAL, C_METAL, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_METAL, C_METAL, 0x8400, 0x8400, C_METAL, C_METAL, C_METAL, C_METAL, 0x8400, C_METAL, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_METAL, C_METAL, 0x8400, COLOR_WHITE, COLOR_WHITE, 0x8400, C_METAL, C_METAL, 0x8400, COLOR_WHITE, C_METAL, C_METAL, C_TRANS, C_TRANS, C_TRANS},
    {C_METAL, C_METAL, 0x8400, COLOR_WHITE, 0x8400, 0x8400, C_METAL, COLOR_WHITE, COLOR_WHITE, C_METAL, 0x8400, 0x8400, C_METAL, C_METAL, C_TRANS, C_TRANS},
    {C_METAL, 0x8400, COLOR_WHITE, 0x8400, 0x8400, C_METAL, C_METAL, COLOR_YELLOW, COLOR_YELLOW, C_METAL, C_METAL, 0x8400, 0x8400, C_METAL, C_TRANS, C_TRANS},
    {C_METAL, 0x8400, 0x8400, C_METAL, C_METAL, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, C_METAL, C_METAL, 0x8400, C_METAL, C_TRANS, C_TRANS},
    {C_METAL, C_METAL, C_METAL, C_METAL, COLOR_YELLOW, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_YELLOW, C_METAL, C_METAL, C_METAL, C_METAL, C_TRANS, C_TRANS},
    {C_TRANS, C_METAL, C_METAL, COLOR_YELLOW, COLOR_WHITE, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_WHITE, COLOR_YELLOW, C_METAL, C_METAL, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_METAL, C_METAL, COLOR_YELLOW, COLOR_WHITE, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_WHITE, COLOR_YELLOW, C_METAL, C_METAL, C_TRANS, C_TRANS, C_TRANS},
    {C_METAL, C_METAL, C_METAL, C_METAL, COLOR_YELLOW, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_YELLOW, C_METAL, C_METAL, C_METAL, C_METAL, C_TRANS, C_TRANS},
    {C_METAL, 0x8400, 0x8400, C_METAL, C_METAL, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, C_METAL, C_METAL, 0x8400, C_METAL, C_TRANS, C_TRANS},
    {C_METAL, 0x8400, COLOR_WHITE, 0x8400, 0x8400, C_METAL, C_METAL, COLOR_YELLOW, COLOR_YELLOW, C_METAL, C_METAL, 0x8400, 0x8400, C_METAL, C_TRANS, C_TRANS},
    {C_METAL, C_METAL, 0x8400, COLOR_WHITE, 0x8400, 0x8400, C_METAL, COLOR_WHITE, COLOR_WHITE, C_METAL, 0x8400, 0x8400, C_METAL, C_METAL, C_TRANS, C_TRANS},
    {C_TRANS, C_METAL, C_METAL, 0x8400, COLOR_WHITE, COLOR_WHITE, 0x8400, C_METAL, C_METAL, 0x8400, COLOR_WHITE, C_METAL, C_METAL, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_METAL, C_METAL, 0x8400, 0x8400, C_METAL, C_METAL, C_METAL, C_METAL, 0x8400, C_METAL, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_METAL, C_METAL, C_METAL, C_METAL, C_METAL, C_METAL, C_METAL, C_METAL, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS}
};

// 16x16 Boss Plasma Dragon Sprite (Dual-Headed Crimson Dragon Ship)
const uint16_t sprite_boss_dragon[16][16] = {
    {COLOR_RED, COLOR_RED, C_ORANGE, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, C_ORANGE},
    {COLOR_RED, COLOR_WHITE, COLOR_YELLOW, COLOR_RED, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_WHITE, COLOR_YELLOW, COLOR_RED},
    {C_ORANGE, COLOR_YELLOW, COLOR_WHITE, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_YELLOW, C_ORANGE},
    {C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS},
    {C_TRANS, C_TRANS, C_ORANGE, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_ORANGE, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_ORANGE, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_RED, C_ORANGE, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_WHITE, COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_WHITE, COLOR_RED, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_WHITE, COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_WHITE, COLOR_RED, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_ORANGE, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_RED, C_ORANGE, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_ORANGE, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_ORANGE, C_TRANS, C_TRANS},
    {C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS},
    {C_ORANGE, COLOR_YELLOW, COLOR_WHITE, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_YELLOW, C_ORANGE},
    {COLOR_RED, COLOR_WHITE, COLOR_YELLOW, COLOR_RED, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_WHITE, COLOR_YELLOW, COLOR_RED},
    {COLOR_RED, COLOR_RED, C_ORANGE, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, C_ORANGE}
};

// 16x16 Boss Chrono Sphere Sprite (Time-Shifting Blue/White Temporal Orb)
const uint16_t sprite_boss_chrono[16][16] = {
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, C_CYAN, C_CYAN, C_TRANS, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, C_CYAN, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, C_CYAN, C_TRANS, C_TRANS},
    {C_TRANS, C_CYAN, COLOR_WHITE, C_CYAN, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, C_CYAN, C_CYAN, C_CYAN, COLOR_WHITE, C_CYAN, C_TRANS},
    {C_TRANS, C_CYAN, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, C_CYAN, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, C_CYAN, C_CYAN, C_TRANS},
    {C_CYAN, COLOR_WHITE, C_CYAN, COLOR_WHITE, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, C_CYAN, C_CYAN, COLOR_WHITE, C_CYAN, COLOR_WHITE, C_CYAN},
    {C_CYAN, COLOR_WHITE, C_CYAN, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, C_CYAN, C_CYAN, C_CYAN, COLOR_WHITE, C_CYAN},
    {COLOR_WHITE, C_CYAN, COLOR_WHITE, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, C_CYAN, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, COLOR_WHITE, C_CYAN, COLOR_WHITE},
    {COLOR_WHITE, C_CYAN, COLOR_WHITE, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, COLOR_WHITE, C_CYAN, COLOR_WHITE},
    {COLOR_WHITE, C_CYAN, COLOR_WHITE, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, COLOR_WHITE, C_CYAN, COLOR_WHITE},
    {COLOR_WHITE, C_CYAN, COLOR_WHITE, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, C_CYAN, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, COLOR_WHITE, C_CYAN, COLOR_WHITE},
    {C_CYAN, COLOR_WHITE, C_CYAN, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, C_CYAN, C_CYAN, C_CYAN, COLOR_WHITE, C_CYAN},
    {C_CYAN, COLOR_WHITE, C_CYAN, COLOR_WHITE, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, C_CYAN, C_CYAN, COLOR_WHITE, C_CYAN, COLOR_WHITE, C_CYAN},
    {C_TRANS, C_CYAN, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, C_CYAN, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, C_CYAN, C_CYAN, C_TRANS},
    {C_TRANS, C_CYAN, COLOR_WHITE, C_CYAN, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, C_CYAN, C_CYAN, C_CYAN, COLOR_WHITE, C_CYAN, C_TRANS},
    {C_TRANS, C_TRANS, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, C_CYAN, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, C_CYAN, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_CYAN, C_CYAN, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, C_CYAN, C_CYAN, C_TRANS, C_TRANS, C_TRANS, C_TRANS}
};

// 16x16 Boss Dark Nebula Sprite (Shadow Void Vortex Fortress)
const uint16_t sprite_boss_nebula[16][16] = {
    {0x0155, 0x0155, C_TRANS, C_TRANS, C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS, C_TRANS, 0x0155, 0x0155},
    {0x0155, COLOR_MAGENTA, 0x0155, C_TRANS, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, C_TRANS, 0x0155, COLOR_MAGENTA, 0x0155},
    {C_TRANS, 0x0155, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, 0x0155, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, 0x0155, 0x0155, COLOR_WHITE, COLOR_WHITE, 0x0155, 0x0155, COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, C_TRANS, C_TRANS},
    {C_TRANS, COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, 0x0155, COLOR_WHITE, COLOR_WHITE, 0x0155, 0x0155, COLOR_WHITE, COLOR_WHITE, 0x0155, COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, C_TRANS},
    {COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, 0x0155, COLOR_WHITE, 0x0155, 0x0155, COLOR_MAGENTA, COLOR_MAGENTA, 0x0155, 0x0155, COLOR_WHITE, 0x0155, COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA},
    {COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, 0x0155, COLOR_WHITE, 0x0155, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, 0x0155, COLOR_WHITE, 0x0155, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA},
    {COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, 0x0155, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, 0x0155, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA},
    {COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, 0x0155, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, 0x0155, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA},
    {COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, 0x0155, COLOR_WHITE, 0x0155, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, 0x0155, COLOR_WHITE, 0x0155, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA},
    {COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, 0x0155, COLOR_WHITE, 0x0155, 0x0155, COLOR_MAGENTA, COLOR_MAGENTA, 0x0155, 0x0155, COLOR_WHITE, 0x0155, COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA},
    {C_TRANS, COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, 0x0155, COLOR_WHITE, COLOR_WHITE, 0x0155, 0x0155, COLOR_WHITE, COLOR_WHITE, 0x0155, COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, 0x0155, 0x0155, COLOR_WHITE, COLOR_WHITE, 0x0155, 0x0155, COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, C_TRANS, C_TRANS},
    {C_TRANS, 0x0155, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, 0x0155, C_TRANS},
    {0x0155, COLOR_MAGENTA, 0x0155, C_TRANS, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_WHITE, COLOR_MAGENTA, C_TRANS, 0x0155, COLOR_MAGENTA, 0x0155},
    {0x0155, 0x0155, C_TRANS, C_TRANS, C_TRANS, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS, C_TRANS, 0x0155, 0x0155}
};

// 16x16 Boss Omega Overlord Sprite (Golden 3D Final Mecha Overlord)
const uint16_t sprite_boss_omega[16][16] = {
    {COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS, COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW},
    {COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW},
    {COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW},
    {C_TRANS, COLOR_YELLOW, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_RED, COLOR_YELLOW, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_YELLOW, COLOR_RED, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_RED, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_RED, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_RED, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_RED, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_RED, COLOR_YELLOW, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_YELLOW, COLOR_RED, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, C_TRANS, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW, C_TRANS, C_TRANS},
    {C_TRANS, COLOR_YELLOW, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, C_TRANS},
    {COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW},
    {COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW},
    {COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW, C_TRANS, C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS, C_TRANS, COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW}
};

// 8x8 Shielded Armored Enemy Sprite (2 HP Cyan Armored Ship)
const uint16_t sprite_enemy_shielded[8][8] = {
    {C_TRANS,   C_CYAN,    C_CYAN,    C_CYAN,    C_CYAN,    C_CYAN,    C_TRANS,   C_TRANS},
    {C_CYAN,    COLOR_WHITE, C_CYAN,    0x0155,    0x0155,    C_CYAN,    C_CYAN,    C_TRANS},
    {C_CYAN,    COLOR_WHITE, C_CYAN,    COLOR_WHITE, COLOR_WHITE, C_CYAN,    COLOR_RED, C_TRANS},
    {COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_YELLOW},
    {COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_YELLOW},
    {C_CYAN,    COLOR_WHITE, C_CYAN,    COLOR_WHITE, COLOR_WHITE, C_CYAN,    COLOR_RED, C_TRANS},
    {C_CYAN,    COLOR_WHITE, C_CYAN,    0x0155,    0x0155,    C_CYAN,    C_CYAN,    C_TRANS},
    {C_TRANS,   C_CYAN,    C_CYAN,    C_CYAN,    C_CYAN,    C_CYAN,    C_TRANS,   C_TRANS}
};

// 8x8 Swarmer Interceptor Sprite (Fast Purple Arrowhead)
const uint16_t sprite_enemy_swarmer[8][8] = {
    {C_TRANS,   C_TRANS,   C_TRANS,   COLOR_MAGENTA, C_TRANS, C_TRANS,   C_TRANS,   C_TRANS},
    {C_TRANS,   C_TRANS,   COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS,   COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS},
    {COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, COLOR_YELLOW, COLOR_YELLOW, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_YELLOW},
    {COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, COLOR_YELLOW, COLOR_YELLOW, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_YELLOW},
    {C_TRANS,   COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS},
    {C_TRANS,   C_TRANS,   COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS,   C_TRANS,   C_TRANS,   COLOR_MAGENTA, C_TRANS, C_TRANS,   C_TRANS,   C_TRANS}
};

// 8x8 Turret Orbiter Sprite (Orange Dual Laser Turret)
const uint16_t sprite_enemy_turret[8][8] = {
    {C_TRANS,   C_ORANGE,  C_ORANGE,  C_ORANGE,  C_ORANGE,  C_ORANGE,  C_TRANS,   C_TRANS},
    {C_ORANGE,  COLOR_WHITE, COLOR_YELLOW, C_ORANGE, C_ORANGE, COLOR_YELLOW, C_ORANGE, C_TRANS},
    {C_ORANGE,  COLOR_YELLOW, C_ORANGE,  0xC600,    0xC600,    C_ORANGE,  C_ORANGE,  C_TRANS},
    {C_ORANGE,  C_ORANGE,  0xC600,    COLOR_WHITE, COLOR_WHITE, 0xC600,    C_ORANGE,  COLOR_YELLOW},
    {C_ORANGE,  C_ORANGE,  0xC600,    COLOR_WHITE, COLOR_WHITE, 0xC600,    C_ORANGE,  COLOR_YELLOW},
    {C_ORANGE,  COLOR_YELLOW, C_ORANGE,  0xC600,    0xC600,    C_ORANGE,  C_ORANGE,  C_TRANS},
    {C_ORANGE,  COLOR_WHITE, COLOR_YELLOW, C_ORANGE, C_ORANGE, COLOR_YELLOW, C_ORANGE, C_TRANS},
    {C_TRANS,   C_ORANGE,  C_ORANGE,  C_ORANGE,  C_ORANGE,  C_ORANGE,  C_TRANS,   C_TRANS}
};

// 8x8 Phantom Stealth Fighter Sprite (Cloaked Dark Purple & Cyan Stealth Jet)
const uint16_t sprite_enemy_phantom[8][8] = {
    {C_TRANS,   0x0155,    0x0155,    0x0155,    0x0155,    0x0155,    C_TRANS,   C_TRANS},
    {0x0155,    COLOR_WHITE, 0x0155,    COLOR_MAGENTA, COLOR_MAGENTA, 0x0155, 0x0155,   C_TRANS},
    {0x0155,    COLOR_WHITE, 0x0155,    COLOR_WHITE, COLOR_WHITE, 0x0155,    COLOR_MAGENTA, C_TRANS},
    {COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_CYAN},
    {COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_CYAN},
    {0x0155,    COLOR_WHITE, 0x0155,    COLOR_WHITE, COLOR_WHITE, 0x0155,    COLOR_MAGENTA, C_TRANS},
    {0x0155,    COLOR_WHITE, 0x0155,    COLOR_MAGENTA, COLOR_MAGENTA, 0x0155, 0x0155,   C_TRANS},
    {C_TRANS,   0x0155,    0x0155,    0x0155,    0x0155,    0x0155,    C_TRANS,   C_TRANS}
};

// 8x8 Minelayer Bomber Sprite (Yellow/Red Heavy Mine Dropper)
const uint16_t sprite_enemy_minelayer[8][8] = {
    {C_TRANS,   COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_YELLOW, C_TRANS, C_TRANS},
    {COLOR_YELLOW, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_YELLOW, C_TRANS},
    {COLOR_YELLOW, COLOR_WHITE, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_RED, C_TRANS},
    {COLOR_RED, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_RED, C_ORANGE},
    {COLOR_RED, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_RED, C_ORANGE},
    {COLOR_YELLOW, COLOR_WHITE, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_RED, C_TRANS},
    {COLOR_YELLOW, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_YELLOW, C_TRANS},
    {C_TRANS,   COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_YELLOW, C_TRANS, C_TRANS}
};

// 8x8 Beamer Beam Emitter Sprite (Bright Cyan Laser Emitter)
const uint16_t sprite_enemy_beamer[8][8] = {
    {C_CYAN,    C_CYAN,    COLOR_WHITE, COLOR_WHITE, C_CYAN,    C_CYAN,    C_TRANS,   C_TRANS},
    {C_CYAN,    COLOR_WHITE, C_CYAN,    C_CYAN,    C_CYAN,    COLOR_WHITE, C_CYAN,    C_TRANS},
    {COLOR_WHITE, C_CYAN,   COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, C_CYAN, COLOR_WHITE, C_TRANS},
    {COLOR_WHITE, C_CYAN,   COLOR_WHITE, COLOR_RED,   COLOR_RED,   COLOR_WHITE, COLOR_WHITE, COLOR_WHITE},
    {COLOR_WHITE, C_CYAN,   COLOR_WHITE, COLOR_RED,   COLOR_RED,   COLOR_WHITE, COLOR_WHITE, COLOR_WHITE},
    {COLOR_WHITE, C_CYAN,   COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, C_CYAN, COLOR_WHITE, C_TRANS},
    {C_CYAN,    COLOR_WHITE, C_CYAN,    C_CYAN,    C_CYAN,    COLOR_WHITE, C_CYAN,    C_TRANS},
    {C_CYAN,    C_CYAN,    COLOR_WHITE, COLOR_WHITE, C_CYAN,    C_CYAN,    C_TRANS,   C_TRANS}
};

// 8x8 Commander Dreadnought Sprite (3 HP Crimson Heavy Flagship)
const uint16_t sprite_enemy_commander[8][8] = {
    {COLOR_RED, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_RED, C_TRANS},
    {COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_RED, C_TRANS},
    {COLOR_RED, COLOR_WHITE, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_YELLOW, C_TRANS},
    {COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE},
    {COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE},
    {COLOR_RED, COLOR_WHITE, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_YELLOW, C_TRANS},
    {COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_RED, C_TRANS},
    {COLOR_RED, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_RED, C_TRANS}
};

// 5x5 Heart Sprite for Lives HUD
const uint16_t sprite_heart[5][5] = {
    {COLOR_RED, COLOR_RED, C_TRANS, COLOR_RED, COLOR_RED},
    {COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED},
    {COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED},
    {C_TRANS, COLOR_RED, COLOR_RED, COLOR_RED, C_TRANS},
    {C_TRANS, C_TRANS, COLOR_RED, C_TRANS, C_TRANS}
};

// 8x8 Shield Matrix Power-up Sprite (Cyan Energy Orb with Specular Core)
const uint16_t sprite_powerup_shield[8][8] = {
    {C_TRANS,   C_TRANS,   C_CYAN,    C_CYAN,    C_CYAN,    C_CYAN,    C_TRANS,   C_TRANS},
    {C_TRANS,   C_CYAN,    COLOR_WHITE, COLOR_WHITE, C_CYAN,     C_CYAN,    C_CYAN,    C_TRANS},
    {C_CYAN,    COLOR_WHITE, COLOR_WHITE, C_CYAN,    0x0155,    0x0155,    C_CYAN,    C_CYAN},
    {C_CYAN,    COLOR_WHITE, C_CYAN,    0x0155,    0x0155,    COLOR_WHITE, C_CYAN,    C_CYAN},
    {C_CYAN,    C_CYAN,    0x0155,    0x0155,    COLOR_WHITE, COLOR_WHITE, C_CYAN,    C_CYAN},
    {C_CYAN,    C_CYAN,    0x0155,    COLOR_WHITE, COLOR_WHITE, C_CYAN,    C_CYAN,    C_CYAN},
    {C_TRANS,   C_CYAN,    C_CYAN,    C_CYAN,    C_CYAN,    C_CYAN,    C_TRANS,   C_TRANS},
    {C_TRANS,   C_TRANS,   C_CYAN,    C_CYAN,    C_CYAN,    C_TRANS,   C_TRANS,   C_TRANS}
};

// 8x8 Double Laser Cannon Power-up Sprite (Twin Golden Barrels with Muzzle Flares)
const uint16_t sprite_powerup_double[8][8] = {
    {C_TRANS,   COLOR_YELLOW, C_ORANGE,  C_TRANS,   C_TRANS,   COLOR_YELLOW, C_ORANGE,  C_TRANS},
    {COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW, C_ORANGE, COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW, C_ORANGE},
    {COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW, C_ORANGE, COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW, C_ORANGE},
    {C_ORANGE,  COLOR_YELLOW, 0xC600,    C_TRANS,   C_ORANGE,  COLOR_YELLOW, 0xC600,    C_TRANS},
    {C_TRANS,   0xC600,    0xC600,    C_TRANS,   C_TRANS,   0xC600,    0xC600,    C_TRANS},
    {C_TRANS,   C_METAL,   C_METAL,   C_METAL,   C_METAL,   C_METAL,   C_TRANS,   C_TRANS},
    {C_TRANS,   C_TRANS,   C_METAL,   COLOR_WHITE, COLOR_WHITE, C_METAL,   C_TRANS,   C_TRANS},
    {C_TRANS,   C_TRANS,   C_TRANS,   C_METAL,   C_METAL,   C_TRANS,   C_TRANS,   C_TRANS}
};

// 8x8 Smart Bomb Warhead Power-up Sprite (Magenta Shell with Fuse Spark)
const uint16_t sprite_powerup_bomb[8][8] = {
    {C_TRANS,   C_TRANS,   C_TRANS,   COLOR_YELLOW, COLOR_WHITE, C_TRANS, C_TRANS,   C_TRANS},
    {C_TRANS,   C_TRANS,   C_ORANGE,  C_ORANGE,  C_TRANS,   C_TRANS,   C_TRANS,   C_TRANS},
    {C_TRANS,   C_METAL,   C_METAL,   C_METAL,   C_METAL,   C_TRANS,   C_TRANS,   C_TRANS},
    {C_TRANS,   COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS},
    {COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS},
    {COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS},
    {COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS},
    {C_TRANS,   COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_TRANS, C_TRANS, C_TRANS}
};

// 8x8 Extra Life Heart Power-up Sprite (3D Beveled Arcade Heart with Specular Shine)
const uint16_t sprite_powerup_life[8][8] = {
    {C_TRANS,   COLOR_RED, COLOR_RED, C_TRANS,   C_TRANS,   COLOR_RED, COLOR_RED, C_TRANS},
    {COLOR_RED, COLOR_WHITE, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_WHITE, COLOR_RED, COLOR_RED},
    {COLOR_RED, COLOR_WHITE, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED},
    {COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED},
    {0x8000,    COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, 0x8000},
    {C_TRANS,   0x8000,    COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, 0x8000,    C_TRANS},
    {C_TRANS,   C_TRANS,   0x8000,    COLOR_RED, COLOR_RED, 0x8000,    C_TRANS,   C_TRANS},
    {C_TRANS,   C_TRANS,   C_TRANS,   0x8000,    0x8000,    C_TRANS,   C_TRANS,   C_TRANS}
};

// 8x8 Spread Triple Laser Power-up Sprite (Orange 3-Way Cannon)
const uint16_t sprite_powerup_spread[8][8] = {
    {COLOR_YELLOW, C_ORANGE,  C_TRANS,   C_TRANS,   C_TRANS,   C_ORANGE,  COLOR_YELLOW, C_TRANS},
    {C_TRANS,   COLOR_YELLOW, C_ORANGE,  COLOR_WHITE, C_ORANGE,  COLOR_YELLOW, C_TRANS,   C_TRANS},
    {C_TRANS,   C_TRANS,   C_METAL,   COLOR_WHITE, C_METAL,   C_TRANS,   C_TRANS,   C_TRANS},
    {C_ORANGE,  COLOR_YELLOW, C_METAL,   COLOR_WHITE, C_METAL,   COLOR_YELLOW, C_ORANGE,  C_TRANS},
    {C_TRANS,   C_TRANS,   C_METAL,   COLOR_WHITE, C_METAL,   C_TRANS,   C_TRANS,   C_TRANS},
    {C_TRANS,   C_TRANS,   C_METAL,   C_METAL,   C_METAL,   C_TRANS,   C_TRANS,   C_TRANS},
    {C_TRANS,   C_TRANS,   C_TRANS,   COLOR_WHITE, C_TRANS,   C_TRANS,   C_TRANS,   C_TRANS},
    {C_TRANS,   C_TRANS,   C_TRANS,   C_TRANS,   C_TRANS,   C_TRANS,   C_TRANS,   C_TRANS}
};

// 8x8 Helper Drone Bot Power-up Sprite (Cyan/Yellow Wingman Drone Orb)
const uint16_t sprite_powerup_drone[8][8] = {
    {C_TRANS,   C_CYAN,    C_CYAN,    COLOR_YELLOW, COLOR_YELLOW, C_CYAN, C_CYAN, C_TRANS},
    {C_CYAN,    COLOR_WHITE, C_CYAN,    COLOR_WHITE, COLOR_WHITE, C_CYAN, COLOR_WHITE, C_CYAN},
    {C_CYAN,    C_CYAN,    COLOR_YELLOW, C_CYAN, C_CYAN, COLOR_YELLOW, C_CYAN, C_CYAN},
    {COLOR_YELLOW, COLOR_WHITE, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, COLOR_WHITE, COLOR_YELLOW},
    {COLOR_YELLOW, COLOR_WHITE, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, COLOR_WHITE, COLOR_YELLOW},
    {C_CYAN,    C_CYAN,    COLOR_YELLOW, C_CYAN, C_CYAN, COLOR_YELLOW, C_CYAN, C_CYAN},
    {C_CYAN,    COLOR_WHITE, C_CYAN,    COLOR_WHITE, COLOR_WHITE, C_CYAN, COLOR_WHITE, C_CYAN},
    {C_TRANS,   C_CYAN,    C_CYAN,    COLOR_YELLOW, COLOR_YELLOW, C_CYAN, C_CYAN, C_TRANS}
};

// 8x8 Singularity Black Hole Power-up Sprite (Deep Dark Purple / Magenta Singularity Orb)
const uint16_t sprite_powerup_blackhole[8][8] = {
    {C_TRANS,       0x380F,      0x780F,      COLOR_MAGENTA, COLOR_MAGENTA, 0x780F,      0x380F,      C_TRANS},
    {0x380F,        0x780F,      COLOR_MAGENTA, COLOR_WHITE,   COLOR_WHITE,   COLOR_MAGENTA, 0x780F,      0x380F},
    {0x780F,        COLOR_MAGENTA, 0x0000,      0x0000,        0x0000,        0x0000,        COLOR_MAGENTA, 0x780F},
    {COLOR_MAGENTA, COLOR_WHITE,   0x0000,      0x0000,        0x0000,        0x0000,        COLOR_WHITE,   COLOR_MAGENTA},
    {COLOR_MAGENTA, COLOR_WHITE,   0x0000,      0x0000,        0x0000,        0x0000,        COLOR_WHITE,   COLOR_MAGENTA},
    {0x780F,        COLOR_MAGENTA, 0x0000,      0x0000,        0x0000,        0x0000,        COLOR_MAGENTA, 0x780F},
    {0x380F,        0x780F,      COLOR_MAGENTA, COLOR_WHITE,   COLOR_WHITE,   COLOR_MAGENTA, 0x780F,      0x380F},
    {C_TRANS,       0x380F,      0x780F,      COLOR_MAGENTA, COLOR_MAGENTA, 0x780F,      0x380F,      C_TRANS}
};

// 10x10 In-game Singularity Black Hole Vortex Graphic
const uint16_t sprite_blackhole_vortex[10][10] = {
    {C_TRANS,   0x780F,    C_CYAN,    COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_CYAN,    0x780F,    C_TRANS},
    {0x780F,    C_CYAN,    COLOR_MAGENTA, 0x780F,      COLOR_WHITE,   COLOR_WHITE,   0x780F,      COLOR_MAGENTA, C_CYAN,    0x780F},
    {C_CYAN,    COLOR_MAGENTA, 0x780F,      0x0000,        0x0000,        0x0000,        0x0000,        0x780F,      COLOR_MAGENTA, C_CYAN},
    {COLOR_MAGENTA, 0x780F,    0x0000,      0x0000,        0x0000,        0x0000,        0x0000,        0x0000,        0x780F,    COLOR_MAGENTA},
    {COLOR_MAGENTA, COLOR_WHITE, 0x0000,    0x0000,        0x0000,        0x0000,        0x0000,        0x0000,        COLOR_WHITE, COLOR_MAGENTA},
    {COLOR_MAGENTA, COLOR_WHITE, 0x0000,    0x0000,        0x0000,        0x0000,        0x0000,        0x0000,        COLOR_WHITE, COLOR_MAGENTA},
    {COLOR_MAGENTA, 0x780F,    0x0000,      0x0000,        0x0000,        0x0000,        0x0000,        0x0000,        0x780F,    COLOR_MAGENTA},
    {C_CYAN,    COLOR_MAGENTA, 0x780F,      0x0000,        0x0000,        0x0000,        0x0000,        0x780F,      COLOR_MAGENTA, C_CYAN},
    {0x780F,    C_CYAN,    COLOR_MAGENTA, 0x780F,      COLOR_WHITE,   COLOR_WHITE,   0x780F,      COLOR_MAGENTA, C_CYAN,    0x780F},
    {C_TRANS,   0x780F,    C_CYAN,    COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, C_CYAN,    0x780F,    C_TRANS}
};

// 8x8 Hyper Overload Power-up Sprite (Lightning Red/Gold Warhead)
const uint16_t sprite_powerup_overload[8][8] = {
    {C_TRANS,   C_TRANS,   COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW, C_TRANS, C_TRANS, C_TRANS},
    {C_TRANS,   COLOR_YELLOW, COLOR_WHITE, COLOR_RED,   COLOR_YELLOW, COLOR_WHITE, C_TRANS, C_TRANS},
    {COLOR_YELLOW, COLOR_WHITE, COLOR_RED,   COLOR_YELLOW, COLOR_WHITE, COLOR_RED, COLOR_YELLOW, C_TRANS},
    {C_TRANS,   COLOR_RED,   COLOR_YELLOW, COLOR_WHITE, COLOR_RED,   COLOR_YELLOW, COLOR_WHITE, COLOR_RED},
    {C_TRANS,   COLOR_RED,   COLOR_YELLOW, COLOR_WHITE, COLOR_RED,   COLOR_YELLOW, COLOR_WHITE, COLOR_RED},
    {COLOR_YELLOW, COLOR_WHITE, COLOR_RED,   COLOR_YELLOW, COLOR_WHITE, COLOR_RED, COLOR_YELLOW, C_TRANS},
    {C_TRANS,   COLOR_YELLOW, COLOR_WHITE, COLOR_RED,   COLOR_YELLOW, COLOR_WHITE, C_TRANS, C_TRANS},
    {C_TRANS,   C_TRANS,   COLOR_YELLOW, COLOR_WHITE, COLOR_YELLOW, C_TRANS, C_TRANS, C_TRANS}
};

// 10x10 Distant Ringed Gas Giant Planet (Subtle Dim Gold Disk with Indigo Ring)
const uint16_t sprite_celestial_gas_giant[10][10] = {
    {C_TRANS,   C_TRANS,   C_TRANS,   0x010E,    0x010E,    C_TRANS,   C_TRANS,   C_TRANS,   C_TRANS,   C_TRANS},
    {C_TRANS,   C_TRANS,   0x010E,    0x39E0,    0x39E0,    0x39E0,    0x010E,    C_TRANS,   C_TRANS,   C_TRANS},
    {C_TRANS,   0x010E,    0x39E0,    0x5200,    0x5200,    0x5200,    0x39E0,    0x010E,    C_TRANS,   C_TRANS},
    {0x010E,    0x39E0,    0x5200,    0x5200,    0x5200,    0x5200,    0x5200,    0x39E0,    0x010E,    C_TRANS},
    {0x010E,    0x39E0,    0x5200,    0x5200,    0x39E0,    0x5200,    0x5200,    0x39E0,    0x010E,    C_TRANS},
    {C_TRANS,   0x010E,    0x5200,    0x5200,    0x5200,    0x5200,    0x5200,    0x39E0,    0x010E,    C_TRANS},
    {C_TRANS,   C_TRANS,   0x010E,    0x39E0,    0x5200,    0x39E0,    0x010E,    0x39E0,    0x010E,    C_TRANS},
    {C_TRANS,   C_TRANS,   C_TRANS,   0x010E,    0x39E0,    0x010E,    0x39E0,    0x5200,    0x010E,    C_TRANS},
    {C_TRANS,   C_TRANS,   C_TRANS,   C_TRANS,   0x010E,    0x010E,    0x5200,    0x39E0,    0x010E,    C_TRANS},
    {C_TRANS,   C_TRANS,   C_TRANS,   C_TRANS,   C_TRANS,   C_TRANS,   0x010E,    0x010E,    C_TRANS,   C_TRANS}
};

// 8x8 Distant Spiral Pinwheel Galaxy (Subtle Deep Indigo & Cyan)
const uint16_t sprite_celestial_galaxy[8][8] = {
    {C_TRANS,   0x010E,    0x010E,    C_TRANS,   C_TRANS,   0x2808,    0x2808,    C_TRANS},
    {0x010E,    0x0110,    0x0110,    0x2808,    0x2808,    0x380F,    0x2808,    C_TRANS},
    {0x010E,    0x0110,    0x2808,    0x380F,    0x380F,    0x0110,    C_TRANS,   C_TRANS},
    {C_TRANS,   0x2808,    0x380F,    COLOR_WHITE, 0x380F,  0x2808,    C_TRANS,   C_TRANS},
    {C_TRANS,   C_TRANS,   0x2808,    0x380F,    COLOR_WHITE, 0x380F,  0x2808,    C_TRANS},
    {C_TRANS,   C_TRANS,   0x0110,    0x380F,    0x380F,    0x2808,    0x0110,    0x010E},
    {C_TRANS,   0x2808,    0x380F,    0x2808,    0x2808,    0x0110,    0x0110,    0x010E},
    {C_TRANS,   0x2808,    0x2808,    C_TRANS,   C_TRANS,   0x010E,    0x010E,    C_TRANS}
};

// 6x6 Helper Drone Ship Sprite (In-game orbiting wingman)
const uint16_t sprite_helper_drone[6][6] = {
    {C_TRANS,   C_CYAN,    COLOR_WHITE, COLOR_WHITE, C_CYAN,    C_TRANS},
    {C_CYAN,    COLOR_WHITE, C_CYAN,    C_CYAN,    COLOR_WHITE, C_CYAN},
    {COLOR_YELLOW, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, COLOR_YELLOW},
    {COLOR_YELLOW, C_CYAN, COLOR_WHITE, COLOR_WHITE, C_CYAN, COLOR_YELLOW},
    {C_CYAN,    COLOR_WHITE, C_CYAN,    C_CYAN,    COLOR_WHITE, C_CYAN},
    {C_TRANS,   C_CYAN,    COLOR_WHITE, COLOR_WHITE, C_CYAN,    C_TRANS}
};

